// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id,created_at,updated_at,name,url,user_id)
VALUES (
$1,
$2,
$3,
$4,
$5,
$6)
RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const selectFeeds = `-- name: SelectFeeds :many
SELECT f.name AS FeedName,f.url AS URL,u.name AS UserName
  FROM feeds f INNER JOIN users u
  ON f.user_id = u.id
`

type SelectFeedsRow struct {
	Feedname string
	Url      string
	Username string
}

func (q *Queries) SelectFeeds(ctx context.Context) ([]SelectFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectFeedsRow
	for rows.Next() {
		var i SelectFeedsRow
		if err := rows.Scan(&i.Feedname, &i.Url, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
